### ISSUE TITLE
nefunčkní

### ISSUE THREAD

**Issue by MikeCZ23** [MrZajic/shadows-of-doubt-cestina#2]
na novou verzi nefunguje, když jsem to zkoušel tak se mi v jazycích němčina neukazala a když jsem jí nechal nastavenou a pak změnil tak to stejně preskocilo na angličtinu

**Comment by MikeCZ23** [comment]
zjistil jsem jak to opravit. Není potřeba nic mazat. stačí když tu tvojí German pojmenuješ jako Czech a vloziš mezi ostatní jazyky spolu s tímhle v té Czech složce.
nové řádky jsou v ang

[LanguageSettings.txt](https://github.com/MrZajic/shadows-of-doubt-cestina/files/14693024/LanguageSettings.txt)

**Comment by Jihus** [comment]
Super, funguje :) Konečně to umožní přidávat další jazyky bez nutnosti šachování s náhradou jiného :)

**Comment by MikeCZ23** [comment]
> Super, funguje :) Konečně to umožní přidávat další jazyky bez nutnosti šachování s náhradou jiného :)

akorát jsem nenašel kod jazyka tak jsem tam dal 15. ale jede to. Pokud tu češtinu dáš k Komunitní Překlady, budeš mít větší dosah a případně editace + to chce dopřeložit
